"use client";
import Image from "next/image";
import {useMemo,useState} from "react";
import {AirplaneTilt,CalendarBlank,CalendarDots,ClipboardText,DotsThree,House,ShieldCheck,UsersThree,MagnifyingGlass,Bell,Plus,X,ArrowRight,List,Sun,CheckCircle,WarningCircle,Clock} from "@phosphor-icons/react";

type Page="dashboard"|"flights"|"absences"|"operations"|"management"|"disciplinaries"|"loa";
const flights=[
 {code:"J2 742",route:"Manchester → Palma",time:"Tue 25 Aug · 06:20",aircraft:"Airbus A321neo",status:"Assigned"},
 {code:"J2 118",route:"Edinburgh → Faro",time:"Wed 26 Aug · 09:45",aircraft:"Boeing 737-800",status:"Open"},
 {code:"J2 601",route:"Birmingham → Tenerife",time:"Fri 28 Aug · 14:10",aircraft:"Airbus A320",status:"Briefing"},
 {code:"J2 927",route:"Leeds → Alicante",time:"Sun 30 Aug · 07:35",aircraft:"Boeing 737-800",status:"Assigned"}
];
const nav=[
 {group:"Workspace",items:[["dashboard","Overview",House],["flights","My roster",CalendarBlank],["absences","Time off",ClipboardText]]},
 {group:"Operations",items:[["operations","Operations hub",AirplaneTilt],["management","Flight management",DotsThree]]},
 {group:"People",items:[["disciplinaries","People records",ShieldCheck],["loa","Leave management",CalendarDots]]}
] as const;
function Button({children,kind="primary",onClick}:{children:React.ReactNode,kind?:"primary"|"secondary"|"ghost",onClick?:()=>void}){return <button className={`btn ${kind}`} onClick={onClick}>{children}</button>}
function Stat({label,value,note,tone="navy"}:{label:string,value:string,note:string,tone?:string}){return <div className="card stat"><p>{label}</p><strong className={tone}>{value}</strong><span>{note}</span></div>}
function Shell(){const [page,setPage]=useState<Page>("dashboard");const [open,setOpen]=useState(false);const [search,setSearch]=useState("");const [toast,setToast]=useState("");const title={dashboard:"Good afternoon, Hannah",flights:"My roster",absences:"Time off",operations:"Operations hub",management:"Flight management",disciplinaries:"People records",loa:"Leave management"}[page];function action(msg:string){setToast(msg);setTimeout(()=>setToast(""),2600)}
 return <div className="app">
  <aside className={open?"sidebar open":"sidebar"}><div className="brand"><div className="brandmark"><AirplaneTilt weight="fill"/></div><div><b>jet<span>2</span> eCrew</b><small>Crew operations</small></div><button className="mobile-close" onClick={()=>setOpen(false)}><X/></button></div><div className="profile"><div className="avatar">HC</div><div><b>Hannah Cole</b><small>Cabin crew · MAN</small></div></div><nav>{nav.map(s=><div className="navgroup" key={s.group}><p>{s.group}</p>{s.items.map(([id,label,Icon])=><button key={id} className={page===id?"active":""} onClick={()=>{setPage(id);setOpen(false)}}><Icon size={20}/><span>{label}</span></button>)}</div>)}</nav><div className="sidefoot"><Sun/><span>Light mode</span><i/></div></aside>
  <div className="main"><header><button className="menu" onClick={()=>setOpen(true)}><List/></button><div><small>CREW OPERATIONS</small><h1>{title}</h1></div><div className="header-actions"><button className="iconbtn"><Bell/><em>3</em></button><div className="mini-profile"><div className="avatar">HC</div><span><b>Hannah Cole</b><small>Crew member</small></span></div></div></header>
   <main>{page==="dashboard"&&<Dashboard go={setPage}/>} {page==="flights"&&<Flights search={search} setSearch={setSearch}/>} {page==="absences"&&<Absences action={action}/>} {page==="operations"&&<Operations action={action}/>} {page==="management"&&<Management action={action}/>} {page==="disciplinaries"&&<Records action={action}/>} {page==="loa"&&<Leave action={action}/>}</main>
  </div>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>} {toast&&<div className="toast"><CheckCircle weight="fill"/>{toast}</div>}
 </div>}
function Dashboard({go}:{go:(p:Page)=>void}){return <div className="content"><section className="hero"><Image src="/aviation-hero.jpg" alt="Aircraft wing above the clouds at sunrise" fill priority sizes="(max-width: 900px) 100vw, 80vw"/><div className="heroShade"/><div className="heroCopy"><p>TUESDAY · 25 AUGUST</p><h2>Your next departure<br/>is ready for you.</h2><Button onClick={()=>go("flights")}>View today’s roster <ArrowRight/></Button></div><div className="heroFlight"><span>NEXT FLIGHT</span><b>J2 742</b><small>Manchester → Palma</small><div><p><Clock/> Briefing <strong>05:35</strong></p><p><AirplaneTilt/> Departure <strong>06:20</strong></p></div></div></section><div className="grid stats"><Stat label="Flights this week" value="4" note="2 sectors remaining"/><Stat label="Duty hours" value="18h 40m" note="Within your roster limit" tone="green"/><Stat label="Annual leave" value="12 days" note="Available to request" tone="coral"/></div><section className="split"><div className="card"><div className="sectionHead"><div><small>UP NEXT</small><h3>Upcoming roster</h3></div><button onClick={()=>go("flights")}>View all <ArrowRight/></button></div>{flights.slice(0,3).map(f=><div className="flightrow" key={f.code}><div className="plane"><AirplaneTilt/></div><div><b>{f.code}</b><span>{f.route}</span></div><p>{f.time}</p><i className={f.status.toLowerCase()}>{f.status}</i></div>)}</div><div className="card activity"><div className="sectionHead"><div><small>LATEST</small><h3>Crew updates</h3></div></div><article><CheckCircle weight="fill"/><div><b>Roster published</b><p>Your September roster is now available.</p><small>18 min ago</small></div></article><article><Bell weight="fill"/><div><b>Briefing reminder</b><p>J2 742 briefing opens at 05:35 tomorrow.</p><small>2 hours ago</small></div></article></div></section></div>}
function PageTop({eyebrow,title,desc,action}:{eyebrow:string,title:string,desc:string,action?:React.ReactNode}){return <div className="pagetop"><div><small>{eyebrow}</small><h2>{title}</h2><p>{desc}</p></div>{action}</div>}
function Flights({search,setSearch}:{search:string,setSearch:(s:string)=>void}){const filtered=useMemo(()=>flights.filter(f=>Object.values(f).join(" ").toLowerCase().includes(search.toLowerCase())),[search]);return <div className="content"><PageTop eyebrow="ROSTER / WEEK 35" title="Your week in the air" desc="Four flights, three destinations and one clear view of the week ahead."/><div className="grid stats"><Stat label="Scheduled flights" value="4" note="25–30 August"/><Stat label="Crewed sectors" value="3" note="All details confirmed" tone="green"/><Stat label="Open positions" value="1" note="Available to bid" tone="gold"/></div><div className="toolbar"><label><MagnifyingGlass/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search flight, route or aircraft"/></label><Button kind="secondary"><CalendarBlank/> This week</Button></div><div className="flightlist">{filtered.map(f=><div className="flightcard" key={f.code}><div className="plane"><AirplaneTilt/></div><div className="flightmain"><b>{f.code}</b><span>{f.route}</span></div><div><small>DATE & TIME</small><b>{f.time}</b></div><div><small>AIRCRAFT</small><b>{f.aircraft}</b></div><i className={f.status.toLowerCase()}>{f.status}</i><button>Details <ArrowRight/></button></div>)}</div></div>}
function Absences({action}:{action:(s:string)=>void}){return <div className="content"><PageTop eyebrow="PEOPLE / TIME OFF" title="Plan time away" desc="Your balance, requests and approvals — all together." action={<Button onClick={()=>action("Time-off request started") }><Plus/> Request time off</Button>}/><div className="grid stats"><Stat label="Days available" value="12" note="2026 allowance" tone="green"/><Stat label="Pending requests" value="1" note="Awaiting review" tone="gold"/><Stat label="Approved this year" value="8" note="Across 2 requests"/></div><div className="card tablecard"><div className="sectionHead"><div><small>MY REQUESTS</small><h3>Request history</h3></div></div><div className="requestrow"><div className="plane"><CalendarBlank/></div><div><b>Summer leave</b><span>14–18 September · 5 days</span></div><i className="briefing">Pending review</i><button>View</button></div><div className="requestrow"><div className="plane greenbg"><CheckCircle/></div><div><b>Family event</b><span>10–12 June · 3 days</span></div><i className="assigned">Approved</i><button>View</button></div></div></div>}
function Operations({action}:{action:(s:string)=>void}){return <div className="content"><PageTop eyebrow="OPERATIONS / CONTROL CENTRE" title="Everything running smoothly" desc="A live view of operational readiness across your network." action={<Button kind="secondary" onClick={()=>action("Operations synced just now")}>Sync operations</Button>}/><div className="grid stats"><Stat label="Flight operations" value="28" note="Flights on today’s schedule"/><Stat label="Crew readiness" value="96%" note="Assigned crew marked ready" tone="green"/><Stat label="System access" value="Active" note="All integrations verified" tone="green"/></div><div className="card tablecard"><div className="sectionHead"><div><small>LIVE ACTIVITY</small><h3>Operations updates</h3></div><span className="live">● LIVE</span></div>{["Roster sync completed|All assigned crew records are current.|2 min ago","Flight J2 118 opened|One cabin crew position remains available.|18 min ago","Weather review complete|No disruption expected across the network.|34 min ago"].map(x=>{const [a,b,c]=x.split("|");return <div className="updaterow" key={a}><i/><div><b>{a}</b><span>{b}</span></div><small>{c}</small></div>})}</div></div>}
function Management({action}:{action:(s:string)=>void}){return <div className="content"><PageTop eyebrow="OPERATIONS / FLIGHTS" title="Flight management" desc="Manage schedules, crew assignments and live flight status." action={<Button onClick={()=>action("New flight draft created")}><Plus/> Add flight</Button>}/><div className="grid stats"><Stat label="Today’s flights" value="8" note="Across 6 destinations"/><Stat label="Fully crewed" value="7" note="87.5% coverage" tone="green"/><Stat label="Needs attention" value="1" note="J2 118 · cabin crew" tone="gold"/></div><div className="flightlist">{flights.map(f=><div className="flightcard" key={f.code}><div className="plane"><AirplaneTilt/></div><div className="flightmain"><b>{f.code}</b><span>{f.route}</span></div><div><small>DEPARTURE</small><b>{f.time}</b></div><div><small>CREW</small><b>{f.status==="Open"?"5 / 6":"6 / 6"}</b></div><i className={f.status.toLowerCase()}>{f.status}</i><button onClick={()=>action(`${f.code} opened`)}>Manage <ArrowRight/></button></div>)}</div></div>}
function Records({action}:{action:(s:string)=>void}){const [modal,setModal]=useState(false);return <div className="content"><PageTop eyebrow="PEOPLE / RECORDS" title="People records" desc="Keep sensitive staff records clear, consistent and accountable." action={<Button onClick={()=>setModal(true)}><Plus/> Record action</Button>}/><div className="grid stats four"><Stat label="Total records" value="3" note="All time"/><Stat label="Informal notes" value="2" note="Guidance recorded" tone="gold"/><Stat label="Written actions" value="1" note="Currently active" tone="coral"/><Stat label="Closed" value="0" note="No archived cases" tone="green"/></div><div className="card empty"><ShieldCheck/><h3>Records are up to date</h3><p>Use Record action to add a confidential staff record.</p></div>{modal&&<Modal title="Record people action" close={()=>setModal(false)} submit={()=>{setModal(false);action("People record saved")}}/>}</div>}
function Leave({action}:{action:(s:string)=>void}){return <div className="content"><PageTop eyebrow="PEOPLE / EXTENDED LEAVE" title="Leave management" desc="Review longer-term leave requests and upcoming returns." action={<Button onClick={()=>action("Leave request started")}><Plus/> New leave request</Button>}/><div className="grid stats"><Stat label="Awaiting review" value="2" note="Oldest is 3 days" tone="gold"/><Stat label="Approved leave" value="4" note="Currently away" tone="green"/><Stat label="Returning this week" value="1" note="Friday · 28 August"/></div><div className="card tablecard"><div className="sectionHead"><div><small>LEAVE REGISTER</small><h3>Active requests</h3></div></div>{["Amelia Hart|Parental leave|1 Oct 2026 – 31 Mar 2027|Pending","Jordan Singh|Career break|15 Nov 2026 – 15 Feb 2027|Pending"].map(x=>{const [a,b,c,d]=x.split("|");return <div className="requestrow" key={a}><div className="avatar">{a.split(" ").map(y=>y[0]).join("")}</div><div><b>{a}</b><span>{b} · {c}</span></div><i className="briefing">{d}</i><button>Review</button></div>})}</div></div>}
function Modal({title,close,submit}:{title:string,close:()=>void,submit:()=>void}){return <div className="modalback"><div className="modal"><button className="modalx" onClick={close}><X/></button><small>NEW CONFIDENTIAL RECORD</small><h2>{title}</h2><label>Team member<input placeholder="Search or enter a name"/></label><label>Action type<select><option>Informal guidance</option><option>Written warning</option><option>Performance support</option></select></label><label>Reason<textarea placeholder="Describe the action and add supporting context…"/></label><div><Button kind="secondary" onClick={close}>Cancel</Button><Button onClick={submit}>Save record</Button></div></div></div>}
export default function Home(){return <Shell/>}
